apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: training
data:
  ConnectionStrings__WriteConnection: "Host=expense-pg-rw;Port=5432;Database=training1;Username=app;Password=Tiendat788"
  ConnectionStrings__ReadConnection: "Host=expense-pg-ro;Port=5432;Database=training1;Username=app;Password=Tiendat788"
  Jwt__Secret: "MSDFAJSD9832BZXF78ASDF6YSD78FBDSMSDIF23948DNFKSD8723234239847BKSDF!"
  Jwt__Issuer: "ExpenseTracker"
  Jwt__Audience: "ExpenseTrackerUsers"
  Jwt__ExpiryMinutes: "60"

---
apiVersion: v1
kind: Service
metadata:
  name: expense-api-service
  namespace: training
spec:
  type: NodePort
  selector:
    app: expense-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
  namespace: training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: expense-api
          image: training-expensetracker-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__WriteConnection
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: ConnectionStrings__WriteConnection
            - name: ConnectionStrings__ReadConnection
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: ConnectionStrings__ReadConnection
            - name: Jwt__Secret
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: Jwt__Secret
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: Jwt__Audience
            - name: Jwt__ExpiryMinutes
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: Jwt__ExpiryMinutes
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
