apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: training
data:
  # Kết nối tới Postgres trong cluster
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=training1;Username=postgres;Password=Tiendat788"

---
apiVersion: v1
kind: Service
metadata:
  name: expense-api-service
  namespace: training
spec:
  type: NodePort
  selector:
    app: expense-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: expense-api
          image: training-expensetracker-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            # Override connection string từ ConfigMap
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: ConnectionStrings__DefaultConnection

